config/routes.rb
Rails.application.routes.draw do
 
  resources :events


  post '/events/:id/attend', to: "events#attend", as: :attend_event

  delete '/events/:id/leave', to: "events#leave", as: :leave_event

  root 'public#index'



  devise_for :users
  resources :users, except: [:new, :create]
  post '/private', to:'private#index'

  
  
  get '/public', to: 'public#index'
  get '/private', to: 'private#index'
  get '/signed_in', to: 'private#signed_in'
  

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
  mount_uploaders :event_images, EventImageUploader
  # belongs_to :user

  belongs_to :creator, class_name: "User", foreign_key: "user_id"
  has_and_belongs_to_many :attendees, class_name: "User", join_table: "events_users"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  mount_uploader :profile_image, UserProfileUploader
  has_many :events  

  has_many :created_events, class_name: "Event", foreign_key: "user_id"
  has_and_belongs_to_many :events_attending, class_name: "Event", join_table: "events_users"     
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters      
    devise_parameter_sanitizer.permit(:account_update, keys: [:username, :first_name, :last_name, :profile_image, :event_image, :created_events, :creator, :events_attending, :attendees])
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username, :first_name, :last_name, :profile_image, :event_image, :created_events, :creator, :events_attending, :attendees])
  end

  def after_sign_in_path_for(resource)
    private_path
  end

end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy, :attend, :leave]
  # before_action :authenticate_user!
  
  def index
    @events = Event.all
  end

  def show
  end

  def attend
    @event.attendees << current_user
    redirect_to event_path(@event)
  end

  def leave
    @event.attendees.delete(current_user)
    redirect_to event_path(@event)
  end

  def new
    @event = Event.new
  end

  def edit
    @event = Event.find(params[:id])
  end

  def create
    @event = current_user.events.new(event_params)
    @event.event_images = params[:event][:event_images]

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
    
  end


  def update
    image_array = @event.event_images

    if params[:images_to_delete]
      params[:images_to_delete].each do |index|
        deleted_image = image_array.delete_at(index.to_i)
        deleted_image.try(:remove!)
      end
    end

    if params[:event][:event_images].present?
      image_array += params[:event][:event_images]
    end

    @event.event_images = image_array

    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:title, :location, :comment, :user_id, :creator)
    end
end

app/controllers/private_controller.rb
class PrivateController < ApplicationController
  
before_action :authenticate_user!

  def index
    
  end

  def signed_in
   
  end
end

app/controllers/public_controller.rb
class PublicController < ApplicationController
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])

  end

  def user_params
    params.require(:user).permit(:username, :profile_image, :created_events)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/private_helper.rb
module PrivateHelper
end

app/helpers/public_helper.rb
module PublicHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/application/_alerts.html.erb
<% if notice %><div class="alert alert-success"><%= notice %></div><% end %>
<% if alert %><div class="alert alert-danger"><%= alert %></div><% end %>

app/views/application/_footer.html.erb
<footer class="footer">
  <span class="text-muted">
  <h6 id="footie">COPYRIGHT © BlackWorks.EST 1987</h6>
    
  </span>
</footer>



<!-- <nav class="navbar navbar-light bg-faded">
  <div class="container">
    <ul class="nav navbar-nav foot">
      <li class="nav-item">
        <p>COPYRIGHT © BlackWorks.EST 1987</p>
      </li>
      <li class="nav-item">
        <p>Contact Us</p>
      </li>
    </ul>
  </div>
</nav>
 -->





   

app/views/application/_header.html.erb
<nav class="navbar navbar-light bg-faded">
 

    
      <div class="container brand">
         <%= link_to image_tag("mainlogo_copy.jpg"), root_path, class: "navbar-brand" %>
        </div> 
        <ul class="nav navbar-nav headtitles">
            <li class="nav-item ">
              <div class="frontheader"><%= link_to "Home", public_path %></div>
            </li>

            <li class="nav-item">
              <div class="frontheader"><%= link_to "Events", events_path %></div>
            </li>
          <% if user_signed_in? %>
            <li class="nav-item">
              <div class="frontheader"><%= link_to current_user.username, current_user %></div>
            </li>
            <li class="nav-item">
              <div class="frontheader"><%= link_to "Create Event", new_event_path %></div>
            </li>
            <li class="nav-item">
              <div class="frontheader"><%= link_to "Log out", destroy_user_session_path, method: :delete %></div>
            </li>
          <% else %>
            <li class="nav-item">
              <div class="frontheader"><%= link_to "Sign In", new_user_session_path %></div>
            </li>
            <li class="nav-item">
             <div class="frontheader"><%= link_to "Register", new_user_registration_path %></div>
            </li>
          <% end %>
          
         
          </ul>
           
      
 
</nav>

app/views/events/_event.html.erb
  <div class="col-md-3">
      <img src="<%=(event.event_images.first.trial) %>" alt="..." class="img-thumbnail">
      <div class="card-block">
        <h4 class="card-title"><%= link_to event.title, event %></h4>
      </div>
    
  </div>




 

app/views/events/_form.html.erb
<%= form_for(event) do |f| %>
  <% if event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% event.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :event_images %><br />
    <% event.event_images.each.with_index do |image, index|%>
      <%= image_tag(image.trial.url) %>
      <%= check_box_tag 'images_to_delete[]', index %> Delete?
    <% end %>

    <%= f.file_field :event_images, multiple: true %>
  </div>

  <div class="field">
    <%= f.label :location %>
    <%= f.text_field :location %>
  </div>

  <div class="field">
    <%= f.label :comment %>
    <%= f.text_area :comment %>
  </div>


  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/events/edit.html.erb
<h1>Editing Event</h1>

<%= render 'form', event: @event %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

app/views/events/index.html.erb
<p id="notice"><%= notice %></p>

<div class="jumbotron jumbotron-fluid">
  <div class="container">
    <h1 class="display-3">Events Trending</h1>
    <p class="lead">What are you up to?</p>
    <%= link_to 'Create a New Event', new_event_path %>
  </div>
</div>

<div class="row">
  <%= render @events %>
</div>

    

app/views/events/new.html.erb
<h1>New Event</h1>

<%= render 'form', event: @event %>

<%= link_to 'Back', events_path %>

app/views/events/show.html.erb
<h1><%=@event.title%></h1>
 <div class="container showevent">
    <div class="container angie">
      <%= image_tag @event.creator.profile_image.user_comment%>
      </div>

    <div class="container angiesays">
      <h3>Event Creator : <%=@event.creator.first_name %>  <%=@event.creator.last_name%></h3>
      <div class="headtitles">Location <%= @event.location%></div>
      <% if !current_user.events_attending.include?(@event) %>
        <div class="headtitles"><%= link_to "Attend Event", attend_event_path(@event), method: :post %></div>
       <% else %>
        <div class="headtitles"> Status: You are attending this event</div>
          <%= link_to "Leave Event", leave_event_path(@event), method: :delete %>
          <% end %>
        </div>
  </div>
  
   
          

<div class="container trump"> 
  <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
    <ol class="carousel-indicators">
      <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
      <li data-target="#carousel-example-generic" data-slide-to="1"></li>
      <li data-target="#carousel-example-generic" data-slide-to="2"></li>
    </ol>

    <div class="carousel-inner" role="listbox">
      <% @event.event_images.each do |image, user| %>
      <% if @event.event_images.first == image %>
        <div class="carousel-item active">
          <%= image_tag(image.event_show.url) %>
        </div>
      <% else %>
        <div class="carousel-item">
          <%= image_tag(image.event_show.url) %>
        </div>
      <% end %>
    <% end %>
    </div>

    <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
      <span class="icon-prev" aria-hidden="true"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
      <span class="icon-next" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
    </a>
  </div>
</div> 

<div class="container showmiddle">
<h3> Attendees:<%=@event.attendees.count %></h3>
</div>

<div class="container showevent">
  <div class="container angie">
    <div class="row">
    <% @event.attendees.each do |attendee| %>
    <div class="col-md-3">
      <p><%= attendee.first_name %></p>
      </div>
      <div class="col-md-3">
      <p><%= attendee.last_name %></p>
      </div>
      <img src="<%=(attendee.profile_image.tiny_comment.url) %>" alt="..." class="thumb-nail">
      <p></p>
    <% end %>
    
   </div>
  </div>
</div>

<div class="container showevent_bottom">
  <div class="container angie">

    <%= link_to "Events", events_path %>
    <%= link_to 'Edit', edit_event_path(@event) %> |
    <%= link_to 'Back', events_path %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WDI21Project2</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  
    <link href="https://fonts.googleapis.com/css?family=Rye|Stint+Ultra+Condensed|Tulpen+One" rel="stylesheet">

  </head>

  <body>
    <%= render "header" %>

    <main class="container page-wrapper">
      <%= render "alerts" %>
      <%= yield %>
    </main>

      <%= render "footer" %>

  </body>
</html>


<div class='login'>
  
</div>

app/views/private/index.html.erb
<h1>What Up <%= current_user.first_name %> </h1>
<div class="container"><%= image_tag current_user.profile_image.user_comment %></div>
<h3>check out what you have going on...</h3>

<div class="container bottom">
  <h2>Events Attending</h2>
  <div class="row">
    <% current_user.events_attending.each do |event| %>
      <div class="col-md-3">
        <div class="hovereffect">
           <img src="<%= event.event_images.first.trial %>" alt="..."> 
           <div class="overlay">
             <h2><%=event.title%></h2>
             <%= link_to "Enter", event, class: 'info' %>
          </div>
          </div>      
        </div>
      <% end %>
  </div> 
</div>

app/views/private/signed_in.html.erb
<h1>Private#signed_in</h1>
<p>Find me in app/views/private/signed_in.html.erb</p>

app/views/user/_user.html.erb
<div class="card">
  <div class="card-block">
    <h4 class="card-title"><%= user.username %></h4>
    <p class="card-text"><%= user.email %></p>
    <p class="card-text"><small class="text-muted">Last updated <%= distance_of_time_in_words(Time.now, user.updated_at) %> ago</small></p>
  </div>
</div>

app/views/users/_user.html.erb
<div class="card">
  <div class="card-block">
    <h4 class="card-title"><%= user.username %></h4>
    <p class="card-text">
    <%= link_to image_tag(user.profile_image.user_profile.url), user_path(user) %></p>
    <p class="card-text"><%= user.email %></p>

 
    <p class="card-text">Events created</p>
    <% user.events.each do |event| %>
      <h4><%= link_to event.title, event %></h4>
      <% event.event_images do |image| %>
      <img src="<%= image_tag image %>">
      <% end %>
    <% end %> 

    <p class="card-text">Events attending</p>
    <% user.events_attending.each do |event| %>
      <h4><%= link_to event.title, event %></h4>
      <p class="card-text"><small class="text-muted">Last updated <%= distance_of_time_in_words(Time.now, user.updated_at) %> ago</small></p>
    <% end %> 
   
  </div>
</div>

app/views/users/index.html.erb
<h1>User#index</h1>
<p>Find me in app/views/user/index.html.erb</p>


<%= render @users %>

app/views/users/show.html.erb
<!-- <div class="jumbotron jumbotron-fluid"> -->

<div class="card">
  <div class="card-block">
    <div class="dp"><%= @user.first_name%> <%= @user.last_name%></div>
    <h1 class="display-3"><%= image_tag current_user.profile_image.user_comment%></h1>
      <%= link_to "Edit My Profile", edit_user_registration_path %>
  </div>
</div>



<div class="container middle">
  <h2>Events Created</h2>
  <div class="row">
    <% @user.events.each do |event| %>
      <div class="col-md-3">
        <div class="hovereffect">
          <img class="img-responsive" src="<%= event.event_images.first.trial %>" alt="">
           <div class="overlay">
             <h2><%=event.title%></h2>
             <a class="info" href="/">Enter</a>
          </div>
          </div>      
        </div>
      <% end %>
  </div> 
</div>

<div class="container bottom">
  <h2>Events Attending</h2>
  <div class="row">
    <% @user.events_attending.each do |event| %>
      <div class="col-md-3">
        <div class="hovereffect">
           <img src="<%= event.event_images.first.trial %>" alt="..."> 
           <div class="overlay">
             <h2><%=event.title%></h2>
             <a class="info" href="/events/:id">Enter</a>
          </div>
          </div>      
        </div>
      <% end %>
  </div> 
</div>


 

      

     